name: valint_discard
description: Discard evidence
author: ""
inputs:
  target:
    description: Target object name format=[<image:tag>, <dir path>, <git url>]
    required: true
  current:
    description: Discard evidence attached to the current context
  interactive:
    description: Force interactive mode for the discard list
  ref:
    description: Evidence store refrence
  silent:
    description: Automatically accept the discard list
  store:
    description: Select evidence store
  cache-enable:
    description: Enable local cache
  config:
    description: Configuration file path
  deliverable:
    description: Mark as deliverable, options=[true, false]
  env:
    description: Environment keys to include in evidence
  gate-name:
    description: Policy Gate name
  gate-type:
    description: Policy Gate type
  input:
    description: Input Evidence target, format (\<parser>:\<file> or \<scheme>:\<name>:\<tag>)
  label:
    description: Add Custom labels
  level:
    description: Log depth level, options=[panic fatal error warning info debug trace]
  log-context:
    description: Attach context to all logs
  log-file:
    description: Output log to file
  output-directory:
    description: Output directory path
    default: ./scribe/valint
  output-file:
    description: Output file name
  pipeline-name:
    description: Pipeline name
  predicate-type:
    description: Custom Predicate type (generic evidence format)
  product-key:
    description: Product Key
  product-version:
    description: Product Version
  scribe-client-id:
    description: Scribe Client ID (deprecated)
  scribe-client-secret:
    description: Scribe Client Token
  scribe-disable:
    description: Disable scribe client
  scribe-enable:
    description: Enable scribe client (deprecated)
  scribe-url:
    description: Scribe API Url
  structured:
    description: Enable structured logger
  timeout:
    description: Timeout duration
  verbose:
    description: Log verbosity level [-v,--verbose=1] = info, [-vv,--verbose=2] = debug
runs:
  using: composite
  steps:
    - shell: bash
      name: Install valint
      run: |2-
        if [ ! -e "$HOME/.scribe/bin/valint" ] || [ -z "$LAZY_INSTALL" ]; then
        	curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/master/gh_install.sh  | sh -s -- -t valint -D
        fi
    - shell: bash
      name: Run valint command
      id: run_valint
      run: |-
        $HOME/.scribe/bin/valint \
        discard \
        ${{ inputs.target }} \
        ${{ inputs.current && '--current=' }}${{ inputs.current }} \
        ${{ inputs.interactive && '--interactive=' }}${{ inputs.interactive }} \
        ${{ inputs.ref && '--ref=' }}${{ inputs.ref }} \
        ${{ inputs.silent && '--silent=' }}${{ inputs.silent }} \
        ${{ inputs.store && '--store=' }}${{ inputs.store }} \
        ${{ inputs.cache-enable && '--cache-enable=' }}${{ inputs.cache-enable }} \
        ${{ inputs.config && '--config=' }}${{ inputs.config }} \
        --context-type=github \
        ${{ inputs.deliverable && '--deliverable=' }}${{ inputs.deliverable }} \
        ${{ inputs.env && '--env=' }}${{ inputs.env }} \
        ${{ inputs.gate-name && '--gate-name=' }}${{ inputs.gate-name }} \
        ${{ inputs.gate-type && '--gate-type=' }}${{ inputs.gate-type }} \
        ${{ inputs.input && '--input=' }}${{ inputs.input }} \
        ${{ inputs.label && '--label=' }}${{ inputs.label }} \
        ${{ inputs.level && '--level=' }}${{ inputs.level }} \
        ${{ inputs.log-context && '--log-context=' }}${{ inputs.log-context }} \
        ${{ inputs.log-file && '--log-file=' }}${{ inputs.log-file }} \
        ${{ inputs.output-directory && '--output-directory=' }}${{ inputs.output-directory }} \
        ${{ inputs.output-file && '--output-file=' }}${{ inputs.output-file }} \
        ${{ inputs.pipeline-name && '--pipeline-name=' }}${{ inputs.pipeline-name }} \
        ${{ inputs.predicate-type && '--predicate-type=' }}${{ inputs.predicate-type }} \
        ${{ inputs.product-key && '--product-key=' }}${{ inputs.product-key }} \
        ${{ inputs.product-version && '--product-version=' }}${{ inputs.product-version }} \
        ${{ inputs.scribe-client-id && '--scribe.client-id=' }}${{ inputs.scribe-client-id }} \
        ${{ inputs.scribe-client-secret && '--scribe.client-secret=' }}${{ inputs.scribe-client-secret }} \
        ${{ inputs.scribe-disable && '--scribe.disable=' }}${{ inputs.scribe-disable }} \
        ${{ inputs.scribe-enable && '--scribe.enable=' }}${{ inputs.scribe-enable }} \
        ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }} \
        ${{ inputs.structured && '--structured=' }}${{ inputs.structured }} \
        ${{ inputs.timeout && '--timeout=' }}${{ inputs.timeout }} \
        ${{ inputs.verbose && '--verbose=' }}${{ inputs.verbose }}
branding:
  icon: shield
  color: green
